version: "3.6"

services:
  database-conservation:
    image: registry.gitlab.com/tortuemat/yulmails/datasets/conservation
    container_name: database
    hostname: database
    environment:
      - POSTGRES_DB=conservation
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  conservation:
    image: registry.gitlab.com/tortuemat/yulmails/services/conservation
    container_name: conservation
    hostname: conservation
    ports:
      - "9090:9090"
      - "8080:8080"
    environment:
      - POSTGRES_DB=conservation
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=database-conservation


