version: "3.6"

services:
  queue-entrypoint:
    image: "redis:5.0.6-alpine"
    container_name: "queue-entrypoint"
    hostname: "queue-entrypoint"

  entrypoint:
    image: "yulmails:0.1.1"
    container_name: "entrypoint"
    hostname: "entrypoint"
    command: [
        "yulctl",
        "entrypoint",
        "--smtp-config",
        "/tmp/entrypoint.json.sample"
    ]
    volumes:
      # to be changed following your needs
      - "${PWD}/conf/entrypoint.json.sample:/tmp/entrypoint.json.sample:ro"
    ports:
      - "2525:2525"
    
  worker-1:
    image: "yulmails:0.1.1"
    command: [
        "yulctl",
        "worker",
        "--worker-config",
        "/tmp/worker.json.sample"
    ]
    volumes:
      # to be changed following your needs
      - "${PWD}/conf/worker.json.sample:/tmp/worker.json.sample:ro"

