apiVersion: apps/v1
kind: Deployment
metadata:
  name: conservation-deployment
  labels:
    app: conservation
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: conservation
  template:
    metadata:
      labels:
        app: conservation
    spec:
      containers:
      - name: conservation
        image: registry.gitlab.com/tortuemat/yulmails/services/conservation
        env:
        - name: POSTGRES_DB
          value: yulmails
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_HOST
          value: database
        ports:
        - containerPort: 9090
        - containerPort: 8080
      imagePullSecrets:
      - name: gitlab-reg
---
apiVersion: v1
kind: Service
metadata:
  name: conservation
  labels:
    tier: backend
    app: conservation
spec:
  selector:
    app: conservation
  ports:
  - protocol: TCP
    port: 8080
    name: http
  - protocol: TCP
    port: 9090
    name: grpc

