apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  labels:
    app: database
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: registry.gitlab.com/tortuemat/yulmails/services/database
        env:
        - name: POSTGRES_DB
          value: yulmails
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        ports:
        - containerPort: 5432
      imagePullSecrets:
      - name: gitlab-reg
---
apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    tier: backend
    app: database
spec:
  selector:
    app: database
  ports:
  - protocol: TCP
    port: 5432

