apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: yulmails-ingress
spec:
  rules:
  - host: api.yulmails.fr
    http:
      paths:
      - path: /v1/conservation
        backend:
          serviceName: conservation
          servicePort: 8080
